name: "JFrog CLI Example"
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: info
        run: curl https://elinaf.jfrog.io/artifactory/api/system/ping

