name: "JFrog CLI Example"
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: info
        run: |
          curl -XPUT -H "Authorization: Bearer ${{ secrets.JF_ACCESS_TOKEN }}" ${{ JF_URL }}/artifactory/example-repo-local/file.txt -T file.txt

